
-- ============================================================
--  ConectaBarrio - Esquema transaccional (Oracle 19c)
--  Orden de creacion respeta la integridad referencial
-- ============================================================
 
CREATE TABLE sector (
  sector_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre     VARCHAR2(60) NOT NULL,
  comuna     VARCHAR2(60) NOT NULL,
  CONSTRAINT pk_sector PRIMARY KEY (sector_id)
);
 
CREATE TABLE categoria (
  categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre       VARCHAR2(60) NOT NULL,
  descripcion  VARCHAR2(200),
  CONSTRAINT pk_categoria PRIMARY KEY (categoria_id),
  CONSTRAINT uq_categoria_nombre UNIQUE (nombre)
);
 
CREATE TABLE medio_pago (
  medio_pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre        VARCHAR2(40) NOT NULL,
  activo        CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_medio_pago PRIMARY KEY (medio_pago_id),
  CONSTRAINT uq_medio_pago_nombre UNIQUE (nombre),
  CONSTRAINT ck_medio_pago_activo CHECK (activo IN ('S','N'))
);
 
CREATE TABLE cliente (
  cliente_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(100) NOT NULL,
  email          VARCHAR2(120) NOT NULL,
  telefono       VARCHAR2(20),
  sector_id      NUMBER NOT NULL,
  fecha_registro DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_cliente PRIMARY KEY (cliente_id),
  CONSTRAINT uq_cliente_email UNIQUE (email),
  CONSTRAINT fk_cliente_sector FOREIGN KEY (sector_id) REFERENCES sector (sector_id)
);
 
CREATE TABLE emprendedor (
  emprendedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(100) NOT NULL,
  email          VARCHAR2(120) NOT NULL,
  telefono       VARCHAR2(20),
  fecha_registro DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_emprendedor PRIMARY KEY (emprendedor_id),
  CONSTRAINT uq_emprendedor_email UNIQUE (email)
);
 
CREATE TABLE emprendimiento (
  emprendimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  emprendedor_id    NUMBER NOT NULL,
  sector_id         NUMBER NOT NULL,
  nombre            VARCHAR2(100) NOT NULL,
  tipo              VARCHAR2(20) NOT NULL,
  rating_promedio   NUMBER(3,2) DEFAULT 0 NOT NULL,
  fecha_apertura    DATE DEFAULT SYSDATE NOT NULL,
  activo            CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_emprendimiento PRIMARY KEY (emprendimiento_id),
  CONSTRAINT fk_emp_emprendedor FOREIGN KEY (emprendedor_id) REFERENCES emprendedor (emprendedor_id),
  CONSTRAINT fk_emp_sector FOREIGN KEY (sector_id) REFERENCES sector (sector_id),
  CONSTRAINT ck_emp_tipo CHECK (tipo IN ('ALMACEN','FERIA','SERVICIO')),
  CONSTRAINT ck_emp_rating CHECK (rating_promedio BETWEEN 0 AND 5),
  CONSTRAINT ck_emp_activo CHECK (activo IN ('S','N'))
);
 
CREATE TABLE producto (
  producto_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  emprendimiento_id NUMBER NOT NULL,
  categoria_id      NUMBER NOT NULL,
  nombre            VARCHAR2(100) NOT NULL,
  descripcion       VARCHAR2(300),
  precio            NUMBER(10,2) NOT NULL,
  stock             NUMBER(6) DEFAULT 0 NOT NULL,
  activo            CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_producto PRIMARY KEY (producto_id),
  CONSTRAINT fk_prod_emp FOREIGN KEY (emprendimiento_id) REFERENCES emprendimiento (emprendimiento_id),
  CONSTRAINT fk_prod_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (categoria_id),
  CONSTRAINT ck_prod_precio CHECK (precio > 0),
  CONSTRAINT ck_prod_stock CHECK (stock >= 0),
  CONSTRAINT ck_prod_activo CHECK (activo IN ('S','N'))
);
 
CREATE TABLE repartidor (
  repartidor_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre          VARCHAR2(100) NOT NULL,
  email           VARCHAR2(120) NOT NULL,
  telefono        VARCHAR2(20),
  vehiculo        VARCHAR2(30),
  sector_id       NUMBER NOT NULL,
  disponible      CHAR(1) DEFAULT 'S' NOT NULL,
  rating_promedio NUMBER(3,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_repartidor PRIMARY KEY (repartidor_id),
  CONSTRAINT uq_repartidor_email UNIQUE (email),
  CONSTRAINT fk_rep_sector FOREIGN KEY (sector_id) REFERENCES sector (sector_id),
  CONSTRAINT ck_rep_vehiculo CHECK (vehiculo IN ('BICICLETA','MOTO','AUTO','A_PIE')),
  CONSTRAINT ck_rep_disponible CHECK (disponible IN ('S','N')),
  CONSTRAINT ck_rep_rating CHECK (rating_promedio BETWEEN 0 AND 5)
);
 
CREATE TABLE pedido (
  pedido_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cliente_id        NUMBER NOT NULL,
  emprendimiento_id NUMBER NOT NULL,
  fecha_pedido      DATE DEFAULT SYSDATE NOT NULL,
  estado            VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  direccion_entrega VARCHAR2(200) NOT NULL,
  CONSTRAINT pk_pedido PRIMARY KEY (pedido_id),
  CONSTRAINT fk_ped_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id),
  CONSTRAINT fk_ped_emp FOREIGN KEY (emprendimiento_id) REFERENCES emprendimiento (emprendimiento_id),
  CONSTRAINT ck_ped_estado CHECK (estado IN
     ('PENDIENTE','CONFIRMADO','EN_PREPARACION','EN_RUTA','ENTREGADO','CANCELADO'))
);
 
CREATE TABLE detalle_pedido (
  pedido_id       NUMBER NOT NULL,
  producto_id     NUMBER NOT NULL,
  cantidad        NUMBER(4) NOT NULL,
  precio_unitario NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_detalle PRIMARY KEY (pedido_id, producto_id),
  CONSTRAINT fk_det_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT fk_det_producto FOREIGN KEY (producto_id) REFERENCES producto (producto_id),
  CONSTRAINT ck_det_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_det_precio CHECK (precio_unitario > 0)
);
 
CREATE TABLE pago (
  pago_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id          NUMBER NOT NULL,
  medio_pago_id      NUMBER NOT NULL,
  monto              NUMBER(10,2) NOT NULL,
  estado             VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  fecha_pago         DATE,
  codigo_transaccion VARCHAR2(50),
  CONSTRAINT pk_pago PRIMARY KEY (pago_id),
  CONSTRAINT uq_pago_pedido UNIQUE (pedido_id),
  CONSTRAINT fk_pago_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT fk_pago_medio FOREIGN KEY (medio_pago_id) REFERENCES medio_pago (medio_pago_id),
  CONSTRAINT ck_pago_monto CHECK (monto >= 0),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('PENDIENTE','APROBADO','RECHAZADO'))
);
 
CREATE TABLE entrega (
  entrega_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id           NUMBER NOT NULL,
  repartidor_id       NUMBER NOT NULL,
  fecha_asignacion    DATE DEFAULT SYSDATE,
  fecha_entrega       DATE,
  estado              VARCHAR2(15) DEFAULT 'ASIGNADA' NOT NULL,
  distancia_km        NUMBER(5,2),
  tiempo_estimado_min NUMBER(4),
  CONSTRAINT pk_entrega PRIMARY KEY (entrega_id),
  CONSTRAINT uq_entrega_pedido UNIQUE (pedido_id),
  CONSTRAINT fk_ent_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT fk_ent_repartidor FOREIGN KEY (repartidor_id) REFERENCES repartidor (repartidor_id),
  CONSTRAINT ck_ent_estado CHECK (estado IN ('ASIGNADA','EN_RUTA','ENTREGADA','FALLIDA')),
  CONSTRAINT ck_ent_distancia CHECK (distancia_km >= 0)
);
 
CREATE TABLE calificacion (
  calificacion_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id              NUMBER NOT NULL,
  puntaje_emprendimiento NUMBER(1),
  puntaje_repartidor     NUMBER(1),
  comentario             VARCHAR2(300),
  fecha                  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_calificacion PRIMARY KEY (calificacion_id),
  CONSTRAINT uq_calif_pedido UNIQUE (pedido_id),
  CONSTRAINT fk_calif_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT ck_calif_emp CHECK (puntaje_emprendimiento BETWEEN 1 AND 5),
  CONSTRAINT ck_calif_rep CHECK (puntaje_repartidor BETWEEN 1 AND 5)
);
 
CREATE TABLE movimiento_puntos (
  movimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cliente_id    NUMBER NOT NULL,
  pedido_id     NUMBER,
  tipo          VARCHAR2(10) NOT NULL,
  puntos        NUMBER(6) NOT NULL,
  fecha         DATE DEFAULT SYSDATE NOT NULL,
  descripcion   VARCHAR2(200),
  CONSTRAINT pk_movimiento PRIMARY KEY (movimiento_id),
  CONSTRAINT fk_mov_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id),
  CONSTRAINT fk_mov_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT ck_mov_tipo CHECK (tipo IN ('GANADO','CANJEADO')),
  CONSTRAINT ck_mov_puntos CHECK (puntos > 0)
);
 

-- ------------------ Catalogos ------------------
INSERT INTO sector (sector_id, nombre, comuna) VALUES (1, 'La Florida Centro', 'La Florida');
INSERT INTO sector (sector_id, nombre, comuna) VALUES (2, 'Bajos de Mena',      'Puente Alto');
INSERT INTO sector (sector_id, nombre, comuna) VALUES (3, 'Maipu Poniente',     'Maipu');
INSERT INTO sector (sector_id, nombre, comuna) VALUES (4, 'Nunoa Norte',        'Nunoa');
INSERT INTO sector (sector_id, nombre, comuna) VALUES (5, 'Buin Centro',        'Buin');
 
INSERT INTO categoria (categoria_id, nombre, descripcion) VALUES (1, 'Abarrotes', 'Productos no perecibles de despensa');
INSERT INTO categoria (categoria_id, nombre, descripcion) VALUES (2, 'Frutas y Verduras', 'Productos frescos de feria');
INSERT INTO categoria (categoria_id, nombre, descripcion) VALUES (3, 'Panaderia', 'Panes, pasteleria y masas');
INSERT INTO categoria (categoria_id, nombre, descripcion) VALUES (4, 'Servicios', 'Servicios a domicilio');
INSERT INTO categoria (categoria_id, nombre, descripcion) VALUES (5, 'Bebidas', 'Bebidas y aguas');
 
INSERT INTO medio_pago (medio_pago_id, nombre, activo) VALUES (1, 'Webpay', 'S');
INSERT INTO medio_pago (medio_pago_id, nombre, activo) VALUES (2, 'Transferencia', 'S');
INSERT INTO medio_pago (medio_pago_id, nombre, activo) VALUES (3, 'Efectivo', 'S');
 
-- ------------------ Actores ------------------
INSERT INTO cliente (cliente_id, nombre, email, telefono, sector_id, fecha_registro)
  VALUES (1, 'Camila Rojas',    'camila.rojas@mail.cl',   '+56911111111', 1, DATE '2025-03-10');
INSERT INTO cliente (cliente_id, nombre, email, telefono, sector_id, fecha_registro)
  VALUES (2, 'Diego Fuentes',   'diego.fuentes@mail.cl',  '+56922222222', 2, DATE '2025-03-15');
INSERT INTO cliente (cliente_id, nombre, email, telefono, sector_id, fecha_registro)
  VALUES (3, 'Valentina Soto',  'valentina.soto@mail.cl', '+56933333333', 1, DATE '2025-04-01');
INSERT INTO cliente (cliente_id, nombre, email, telefono, sector_id, fecha_registro)
  VALUES (4, 'Matias Herrera',  'matias.herrera@mail.cl', '+56944444444', 3, DATE '2025-04-20');
INSERT INTO cliente (cliente_id, nombre, email, telefono, sector_id, fecha_registro)
  VALUES (5, 'Josefa Vera',     'josefa.vera@mail.cl',    '+56955555555', 4, DATE '2025-05-05');
INSERT INTO cliente (cliente_id, nombre, email, telefono, sector_id, fecha_registro)
  VALUES (6, 'Tomas Aguilar',   'tomas.aguilar@mail.cl',  '+56966666666', 5, DATE '2025-05-18');
 
INSERT INTO emprendedor (emprendedor_id, nombre, email, telefono, fecha_registro)
  VALUES (1, 'Rosa Miranda',  'rosa.miranda@mail.cl',  '+56977000001', DATE '2025-01-08');
INSERT INTO emprendedor (emprendedor_id, nombre, email, telefono, fecha_registro)
  VALUES (2, 'Luis Caceres',  'luis.caceres@mail.cl',  '+56977000002', DATE '2025-01-12');
INSERT INTO emprendedor (emprendedor_id, nombre, email, telefono, fecha_registro)
  VALUES (3, 'Andrea Pinto',  'andrea.pinto@mail.cl',  '+56977000003', DATE '2025-02-02');
INSERT INTO emprendedor (emprendedor_id, nombre, email, telefono, fecha_registro)
  VALUES (4, 'Jorge Salinas', 'jorge.salinas@mail.cl', '+56977000004', DATE '2025-02-14');
 
INSERT INTO emprendimiento (emprendimiento_id, emprendedor_id, sector_id, nombre, tipo, rating_promedio, fecha_apertura, activo)
  VALUES (1, 1, 1, 'Almacen Dona Rosa',   'ALMACEN',  4.50, DATE '2025-01-20', 'S');
INSERT INTO emprendimiento (emprendimiento_id, emprendedor_id, sector_id, nombre, tipo, rating_promedio, fecha_apertura, activo)
  VALUES (2, 2, 2, 'Verduleria El Sol',   'FERIA',    4.00, DATE '2025-01-25', 'S');
INSERT INTO emprendimiento (emprendimiento_id, emprendedor_id, sector_id, nombre, tipo, rating_promedio, fecha_apertura, activo)
  VALUES (3, 3, 1, 'Panaderia La Espiga', 'ALMACEN',  4.75, DATE '2025-02-10', 'S');
INSERT INTO emprendimiento (emprendimiento_id, emprendedor_id, sector_id, nombre, tipo, rating_promedio, fecha_apertura, activo)
  VALUES (4, 4, 3, 'Servicios Don Jorge', 'SERVICIO', 4.20, DATE '2025-02-20', 'S');
 
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (1, 1, 1, 'Arroz Grado 1 - 1 kg', 'Arroz largo fino', 1290, 50, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (2, 1, 1, 'Aceite Vegetal - 1 L', 'Aceite maravilla', 2490, 30, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (3, 1, 1, 'Fideos - 400 g', 'Fideos spaghetti', 990, 40, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (4, 1, 5, 'Bebida Cola - 1.5 L', 'Bebida gaseosa', 1690, 25, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (5, 1, 5, 'Agua Mineral - 1.5 L', 'Agua sin gas', 990, 60, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (6, 2, 2, 'Tomate - 1 kg', 'Tomate larga vida', 1490, 20, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (7, 2, 2, 'Papas - 5 kg', 'Papa desiree', 3990, 15, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (8, 2, 2, 'Palta Hass - 1 kg', 'Palta de temporada', 5990, 10, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (9, 2, 2, 'Lechuga - unidad', 'Lechuga costina', 890, 30, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (10, 3, 3, 'Pan Amasado - 1 kg', 'Pan amasado del dia', 2490, 25, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (11, 3, 3, 'Marraqueta - 1 kg', 'Marraqueta crujiente', 1990, 40, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (12, 3, 3, 'Empanada de Pino', 'Empanada horneada', 1500, 35, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (13, 3, 3, 'Torta de Chocolate', 'Torta 12 porciones', 12990, 5, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (14, 4, 4, 'Visita Gasfiteria', 'Reparacion domiciliaria', 25000, 100, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (15, 4, 4, 'Visita Electricidad', 'Reparacion electrica', 28000, 100, 'S');
INSERT INTO producto (producto_id, emprendimiento_id, categoria_id, nombre, descripcion, precio, stock, activo) VALUES
  (16, 4, 4, 'Visita Cerrajeria', 'Apertura y cambio de cerradura', 30000, 100, 'S');
 
INSERT INTO repartidor (repartidor_id, nombre, email, telefono, vehiculo, sector_id, disponible, rating_promedio)
  VALUES (1, 'Pedro Nunez',  'pedro.nunez@mail.cl',  '+56988000001', 'MOTO',      1, 'S', 4.60);
INSERT INTO repartidor (repartidor_id, nombre, email, telefono, vehiculo, sector_id, disponible, rating_promedio)
  VALUES (2, 'Ignacio Bravo','ignacio.bravo@mail.cl','+56988000002', 'BICICLETA', 2, 'S', 4.30);
INSERT INTO repartidor (repartidor_id, nombre, email, telefono, vehiculo, sector_id, disponible, rating_promedio)
  VALUES (3, 'Carla Mendez', 'carla.mendez@mail.cl', '+56988000003', 'AUTO',      1, 'N', 4.80);
INSERT INTO repartidor (repartidor_id, nombre, email, telefono, vehiculo, sector_id, disponible, rating_promedio)
  VALUES (4, 'Felipe Torres','felipe.torres@mail.cl','+56988000004', 'MOTO',      3, 'S', 4.10);
 
-- ------------------ Transacciones ------------------
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (1, 1, 1, DATE '2025-06-02', 'ENTREGADO',      'Av. Vicuna Mackenna 5000, La Florida');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (2, 2, 2, DATE '2025-06-03', 'ENTREGADO',      'Pasaje Los Aromos 120, Puente Alto');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (3, 1, 3, DATE '2025-06-05', 'EN_RUTA',        'Av. Vicuna Mackenna 5000, La Florida');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (4, 3, 1, DATE '2025-06-06', 'CONFIRMADO',     'Calle Serrano 340, La Florida');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (5, 4, 4, DATE '2025-06-07', 'ENTREGADO',      'Av. Pajaritos 2200, Maipu');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (6, 5, 2, DATE '2025-06-08', 'PENDIENTE',      'Av. Irarrazaval 3400, Nunoa');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (7, 1, 1, DATE '2025-06-10', 'ENTREGADO',      'Av. Vicuna Mackenna 5000, La Florida');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (8, 6, 3, DATE '2025-06-11', 'EN_PREPARACION', 'Av. Manuel Rodriguez 90, Buin');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (9, 2, 2, DATE '2025-06-12', 'CANCELADO',      'Pasaje Los Aromos 120, Puente Alto');
INSERT INTO pedido (pedido_id, cliente_id, emprendimiento_id, fecha_pedido, estado, direccion_entrega)
  VALUES (10, 4, 1, DATE '2025-06-14', 'ENTREGADO',     'Av. Pajaritos 2200, Maipu');
 
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (1, 1, 2, 1290);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (1, 3, 3, 990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (1, 4, 1, 1690);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (2, 6, 2, 1490);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (2, 8, 1, 5990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (3, 10, 1, 2490);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (3, 12, 4, 1500);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (4, 2, 1, 2490);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (4, 5, 2, 990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (5, 14, 1, 25000);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (6, 7, 1, 3990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (6, 9, 3, 890);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (7, 1, 1, 1290);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (7, 2, 2, 2490);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (8, 11, 2, 1990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (8, 13, 1, 12990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (9, 6, 5, 1490);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (10, 3, 4, 990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (10, 4, 2, 1690);
 
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (1, 1, 1, 6540,  'APROBADO',  DATE '2025-06-02', 'WP-000001');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (2, 2, 1, 8970,  'APROBADO',  DATE '2025-06-03', 'WP-000002');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (3, 3, 2, 8490,  'APROBADO',  DATE '2025-06-05', 'TR-000003');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (4, 4, 1, 4470,  'PENDIENTE', NULL,             NULL);
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (5, 5, 3, 25000, 'APROBADO',  DATE '2025-06-07', 'EF-000005');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (6, 6, 1, 6660,  'PENDIENTE', NULL,             NULL);
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (7, 7, 1, 6270,  'APROBADO',  DATE '2025-06-10', 'WP-000007');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (8, 8, 2, 16970, 'APROBADO',  DATE '2025-06-11', 'TR-000008');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (9, 9, 1, 7450,  'RECHAZADO', DATE '2025-06-12', 'WP-000009');
INSERT INTO pago (pago_id, pedido_id, medio_pago_id, monto, estado, fecha_pago, codigo_transaccion)
  VALUES (10, 10, 3, 7340, 'APROBADO', DATE '2025-06-14', 'EF-000010');
 
INSERT INTO entrega (entrega_id, pedido_id, repartidor_id, fecha_asignacion, fecha_entrega, estado, distancia_km, tiempo_estimado_min)
  VALUES (1, 1, 1, DATE '2025-06-02', DATE '2025-06-02', 'ENTREGADA', 2.30, 25);
INSERT INTO entrega (entrega_id, pedido_id, repartidor_id, fecha_asignacion, fecha_entrega, estado, distancia_km, tiempo_estimado_min)
  VALUES (2, 2, 2, DATE '2025-06-03', DATE '2025-06-03', 'ENTREGADA', 3.10, 30);
INSERT INTO entrega (entrega_id, pedido_id, repartidor_id, fecha_asignacion, fecha_entrega, estado, distancia_km, tiempo_estimado_min)
  VALUES (3, 3, 1, DATE '2025-06-05', NULL,             'EN_RUTA',   1.80, 20);
INSERT INTO entrega (entrega_id, pedido_id, repartidor_id, fecha_asignacion, fecha_entrega, estado, distancia_km, tiempo_estimado_min)
  VALUES (4, 5, 4, DATE '2025-06-07', DATE '2025-06-07', 'ENTREGADA', 5.40, 40);
INSERT INTO entrega (entrega_id, pedido_id, repartidor_id, fecha_asignacion, fecha_entrega, estado, distancia_km, tiempo_estimado_min)
  VALUES (5, 7, 1, DATE '2025-06-10', DATE '2025-06-10', 'ENTREGADA', 2.30, 25);
INSERT INTO entrega (entrega_id, pedido_id, repartidor_id, fecha_asignacion, fecha_entrega, estado, distancia_km, tiempo_estimado_min)
  VALUES (6, 10, 4, DATE '2025-06-14', DATE '2025-06-14', 'ENTREGADA', 4.90, 38);
 
INSERT INTO calificacion (calificacion_id, pedido_id, puntaje_emprendimiento, puntaje_repartidor, comentario, fecha)
  VALUES (1, 1, 5, 5, 'Rapido y todo en orden', DATE '2025-06-02');
INSERT INTO calificacion (calificacion_id, pedido_id, puntaje_emprendimiento, puntaje_repartidor, comentario, fecha)
  VALUES (2, 2, 4, 4, 'Buena verdura, llego a tiempo', DATE '2025-06-03');
INSERT INTO calificacion (calificacion_id, pedido_id, puntaje_emprendimiento, puntaje_repartidor, comentario, fecha)
  VALUES (3, 5, 5, 4, 'Excelente servicio de gasfiteria', DATE '2025-06-07');
INSERT INTO calificacion (calificacion_id, pedido_id, puntaje_emprendimiento, puntaje_repartidor, comentario, fecha)
  VALUES (4, 7, 4, 5, 'Todo bien', DATE '2025-06-10');
INSERT INTO calificacion (calificacion_id, pedido_id, puntaje_emprendimiento, puntaje_repartidor, comentario, fecha)
  VALUES (5, 10, 4, 4, 'Conforme con la compra', DATE '2025-06-14');
 
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion)
  VALUES (1, 1, 1, 'GANADO', 6,  DATE '2025-06-02', 'Puntos por compra pedido 1');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion)
  VALUES (2, 2, 2, 'GANADO', 8,  DATE '2025-06-03', 'Puntos por compra pedido 2');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion)
  VALUES (3, 4, 5, 'GANADO', 25, DATE '2025-06-07', 'Puntos por compra pedido 5');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion)
  VALUES (4, 1, 7, 'GANADO', 6,  DATE '2025-06-10', 'Puntos por compra pedido 7');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion)
  VALUES (5, 4, 10, 'GANADO', 7, DATE '2025-06-14', 'Puntos por compra pedido 10');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion)
  VALUES (6, 1, NULL, 'CANJEADO', 5, DATE '2025-06-15', 'Canje por descuento');
 
COMMIT;


-- como los id son auto al inserta van con el valor por defecto 

ALTER TABLE pago
MODIFY pago_id GENERATED AS IDENTITY
(
    START WITH LIMIT VALUE
);


ALTER TABLE categoria
MODIFY categoria_id GENERATED AS IDENTITY
(
    START WITH LIMIT VALUE
);

